### ISSUE TITLE
Unable to find DartDev snapshot.

### ISSUE THREAD

**Issue by insinfo** [subfuzion/dart-scratch#8] opened 2020-11-27 16:04 UTC
I'm having this problem when I run the docker image, I don't have this problem when I run my Angel Framework app with the standard google/dart:2.10 image

### Dockerfile_jit not work
```Dockerfile
FROM google/dart:2.10 as jubarte2server
WORKDIR /app
ADD pubspec.* /app/
RUN pub get --no-precompile
ADD . /app
RUN pub get --offline
RUN cp .env.example.linux .env
RUN dart compile kernel -o bin/prod.dill bin/prod.dart

FROM subfuzion/dart:slim as jubarte2server-jit
COPY --from=jubarte2server /usr/lib/dart/bin/dart /usr/lib/dart/bin/dart
COPY --from=jubarte2server /root/.pub-cache /root/.pub-cache
COPY --from=jubarte2server /app /app
ENV dbhost=localhost
EXPOSE 3150
ENTRYPOINT ["/usr/lib/dart/bin/dart","/app/bin/server.dill -p 3150 -a 0.0.0.0 --dbhost=$dbhost"]
# docker build -f Dockerfile_jit -t jubarte2server-jit .
# run image
# docker run -e "dbhost=192.168.133.13" -d --name jubarte2server-jit -p 3150:3150 jubarte2server-jit   
# docker run -e "dbhost=192.168.133.13" -i --name jubarte2server-jit -p 3150:3150 jubarte2server-jit   
```

### Dockerfile work
```Dockerfile
FROM google/dart:2.10 as jubarte2server
WORKDIR /app
ADD pubspec.* /app/
RUN pub get --no-precompile
ADD . /app
RUN pub get --offline
ENV dbhost=localhost
RUN cp .env.example.linux .env
CMD /usr/bin/dart run bin/prod.dart -p 3150 -a 0.0.0.0 --dbhost=$dbhost
EXPOSE 3150
# create image
# docker build -t jubarte2server .  
# run image
# docker run -e "dbhost=192.168.133.13" -d --name jubarte2server -p 3150:3150 jubarte2server   
# docker run -e "dbhost=192.168.133.13" -i --name jubarte2server -p 3150:3150 jubarte2server   
```

**Comment by subfuzion** [comment] 2020-11-28 22:07
@insinfo It looks like line #16 is in error:

```
ENTRYPOINT ["/usr/lib/dart/bin/dart","/app/bin/server.dill -p 3150 -a 0.0.0.0 --dbhost=$dbhost"]
```

Your output from line #8 is `-o bin/prod.dill`, so that's what you would need to reference (or else change the output name, but either way be consistent). 

Also, you're not quoting the arguments correctly. I know what you mean to do here, but when using the exec form for `ENTRYPOINT` (as well as `CMD`), each command line argument should be quoted and separated with commas.

```
ENTRYPOINT ["/usr/lib/dart/bin/dart", "/app/bin/prod.dill", "-p", "3150",  "-a", "0.0.0.0", "--dbhost=$dbhost"]
```

or
```
ENTRYPOINT ["/usr/lib/dart/bin/dart", "/app/bin/prod.dill", "-p", "3150",  "-a", "0.0.0.0", "--dbhost", "$dbhost"]
```

Ref: https://docs.docker.com/engine/reference/builder/#exec-form-entrypoint-example

Good luck!

**Comment by subfuzion** [comment] 2020-11-28 22:40
This isn't a bug with `dart:slim`, so I'm closing the issue.

I can't always help with debugging, but I do know personally how frustrating working with `Dockerfile`s can be at times, so feel free to reach out to me (tonypujals@google.com) personally if you need to. I'm most likely to take a look if you email me a link to an issue in **your own repo** (that I can clone, if necessary) describing the problem you're having.

**Comment by insinfo** [comment] 2020-11-30 20:26
No, the error on line 16 was an error when copying and pasting on github, the problem is not there, the problem does not seem to be connected to the command line


#  I tried like this and also hear the same error
```Dockerfile

FROM google/dart:2.10 as jubarte2server
WORKDIR /app
ADD pubspec.* /app/
RUN pub get --no-precompile
ADD . /app
RUN pub get --offline
RUN cp .env.example.linux .env
RUN dart compile kernel -o bin/prod.dill bin/prod.dart

FROM subfuzion/dart:slim as jubarte2server-jit
COPY --from=jubarte2server /usr/lib/dart/bin/dart /usr/lib/dart/bin/dart
COPY --from=jubarte2server /root/.pub-cache /root/.pub-cache
COPY --from=jubarte2server /app /app
ENV dbhost=localhost
EXPOSE 3150
ENTRYPOINT ["/usr/lib/dart/bin/dart","/app/bin/prod.dill -p 3150 -a 0.0.0.0 --dbhost=$dbhost"]
# docker build -f Dockerfile_jit -t jubarte2server-jit .
# executa a imagem
# docker run -e "dbhost=192.168.133.13" -d --name jubarte2server-jit -p 3150:3150 jubarte2server-jit   
# docker run -e "dbhost=192.168.133.13" -i --name jubarte2server-jit -p 3150:3150 jubarte2server-jit  

```
#  I tried like this and also hear the same error
```Dockerfile

FROM google/dart:2.10 as jubarte2server
WORKDIR /app
ADD pubspec.* /app/
RUN pub get --no-precompile
ADD . /app
RUN pub get --offline
RUN cp .env.example.linux .env
#RUN dart compile kernel -o bin/prod.dill bin/prod.dart

FROM subfuzion/dart:slim as jubarte2server-jit
COPY --from=jubarte2server /usr/lib/dart/bin/dart /usr/lib/dart/bin/dart
COPY --from=jubarte2server /root/.pub-cache /root/.pub-cache
COPY --from=jubarte2server /app /app
COPY --from=jubarte2server /app/.env /.env
COPY --from=jubarte2server /app/.env /app/bin/.env 
COPY --from=jubarte2server /app/.env /usr/lib/dart/bin/.env 
ENV dbhost=localhost
EXPOSE 3150
ENTRYPOINT ["/usr/lib/dart/bin/dart","run","/app/bin/prod.dart", "-p", "3150", "-a" ,"0.0.0.0","--dbhost=$dbhost"]
# docker build -f Dockerfile_jit -t jubarte2server-jit .
# executa a imagem
# docker run -e "dbhost=192.168.133.13" -d --name jubarte2server-jit -p 3150:3150 jubarte2server-jit   
# docker run -e "dbhost=192.168.133.13" -i --name jubarte2server-jit -p 3150:3150 jubarte2server-jit   


````

**Comment by insinfo** [comment] 2020-11-30 20:30
On my machine it works correctly

```console
PS D:\MyDartProjects\jubarte2\jubarte2server> dart run .\bin\prod.dart -p 3150
____________   ________________________ 
___    |__  | / /_  ____/__  ____/__  / 
__  /| |_   |/ /_  / __ __  __/  __  /  
_  ___ |  /|  / / /_/ / _  /___  _  /___
/_/  |_/_/ |_/  ____/  /_____/  /_____/ 

A batteries-included, full-featured, full-stack framework in Dart.

https://angel-dart.github.io

Starting `jubarte_angel` application...
[INFO] jubarte_angel: boot_angel.dart  /api APP_ENV: development
[INFO] jubarte_angel: boot_angel.dart  /api APP_ENV: development
[INFO] jubarte_angel: boot_angel.dart  /api APP_ENV: development
[INFO] jubarte_angel: db_connect.dart dbConnect() connect Jubarte 192.168.133.13
[INFO] jubarte_angel: db_connect.dart dbConnect() connect BlogBIT 192.168.133.22
[INFO] jubarte_angel: db_connect.dart dbConnect() connect CEP 10.0.0.22
[INFO] jubarte_angel: db_connect.dart dbConnect() connect Jubarte 192.168.133.13
[INFO] jubarte_angel: db_connect.dart dbConnect() connect BlogBIT 192.168.133.22
[INFO] jubarte_angel: db_connect.dart dbConnect() connect CEP 10.0.0.22
[INFO] jubarte_angel: db_connect.dart dbConnect() connect Jubarte 192.168.133.13
[INFO] jubarte_angel: db_connect.dart dbConnect() connect BlogBIT 192.168.133.22
[INFO] jubarte_angel: db_connect.dart dbConnect() connect CEP 10.0.0.22
[INFO] jubarte_angel: boot_angel.dart  /api APP_ENV: development
[INFO] jubarte_angel: db_connect.dart dbConnect() connect Jubarte 192.168.133.13
[INFO] jubarte_angel: db_connect.dart dbConnect() connect BlogBIT 192.168.133.22
[INFO] jubarte_angel: db_connect.dart dbConnect() connect CEP 10.0.0.22
[INFO] jubarte_angel: Instance #1 listening at http://127.0.0.1:3150
[INFO] jubarte_angel: Instance #3 listening at http://127.0.0.1:3150
[INFO] jubarte_angel: Instance #0 listening at http://127.0.0.1:3150
[INFO] jubarte_angel: Instance #2 listening at http://127.0.0.1:3150

```

**Comment by insinfo** [comment] 2020-11-30 20:36
The AOT version also works correctly if I do it like this

```Dockerfile
FROM google/dart:2.10 as jubarte2server
WORKDIR /app
ADD pubspec.* /app/
RUN pub get --no-precompile
ADD . /app
RUN pub get --offline
RUN cp .env.example.linux /app/.env
RUN dart compile exe /app/bin/prod.dart -o /app/bin/prod

FROM subfuzion/dart:slim as jubarte2server-aot
COPY --from=jubarte2server /bin/sh /bin/sh
COPY --from=jubarte2server /bin/bash /bin/bash
COPY --from=jubarte2server /bin/ls /bin/ls
#libs for /bin/ls
COPY --from=jubarte2server /lib/x86_64-linux-gnu/libpcre.so.3 /lib/x86_64-linux-gnu/libpcre.so.3
COPY --from=jubarte2server /lib/x86_64-linux-gnu/libselinux.so.1 /lib/x86_64-linux-gnu/libselinux.so.1
#libs for /bin/bash
COPY --from=jubarte2server /lib/x86_64-linux-gnu/libtinfo.so.6 /lib/x86_64-linux-gnu/libtinfo.so.6
COPY --from=jubarte2server /lib/x86_64-linux-gnu/libdl.so.2 /lib/x86_64-linux-gnu/libdl.so.2
COPY --from=jubarte2server /lib/x86_64-linux-gnu/libc.so.6 /lib/x86_64-linux-gnu/libc.so.6

COPY --from=jubarte2server /app/.env /app/bin/.env 
COPY --from=jubarte2server /app/.env /.env
COPY --from=jubarte2server /app/.env /usr/lib/.env
COPY --from=jubarte2server /app/.env /usr/bin/.env
COPY --from=jubarte2server /app/.env /root/.env
COPY --from=jubarte2server /app/.env /tmp/.env
COPY --from=jubarte2server /app/bin/prod /app/bin/prod
#COPY --from=jubarte2server /app /app
#variavel de tempo de criação de imagem
#ARG dbhost
#pode ser usada assim
#docker build --build-arg dbhost=localhost
#ou na hora de iniciar um container você pode passar variaves
#ENV dbhost e na hora de executar docker run -e "dbhost=192.168.133.13"
ENV dbhost=localhost
#--no-precompile 
# Optionally build generaed sources.
# RUN pub run build_runner build
#CMD ["sh", "-c", "/usr/bin/dart run bin/prod.dart -p 3150 -a 0.0.0.0 --dbhost ${dbhostr}"] -p 3150 -a 0.0.0.0 --dbhost=$dbhost
EXPOSE 3150
CMD sh -c cd /app/bin/ && /app/bin/prod
#ENTRYPOINT ["/bin/bash"]
#ENTRYPOINT ["/bin/sh -c ls"]
#ENTRYPOINT ["/app/bin/prod"]
#CMD ["/bin/dart", "run", "./bin/prod.dart","-p","3150","-a", "0.0.0.0","-dbhost=","$dbhost"]
#ENTRYPOINT ["/usr/bin/dart", "run", "./bin/prod.dart","-p","3150","-a", "0.0.0.0","dbhost=",${dbhost}]
# cria a imagem 
# docker build -f Dockerfile_aot -t jubarte2server-aot .
# executa a imagem
#docker rm jubarte2server-aot 
# docker run -e "dbhost=192.168.133.13" -d --name jubarte2server-aot -p 3150:3150 jubarte2server-aot   
# docker run -e "dbhost=192.168.133.13" -i --name jubarte2server-aot -p 3150:3150 jubarte2server-aot    



```

```console
PS D:\MyDartProjects\jubarte2\jubarte2server>  docker build -f Dockerfile_aot -t jubarte2server-aot .
[+] Building 31.2s (30/30) FINISHED
 => [internal] load build definition from Dockerfile_aot                                                                        0.6s 
 => => transferring dockerfile: 2.57kB                                                                                          0.0s 
 => [internal] load .dockerignore                                                                                               0.9s 
 => => transferring context: 34B                                                                                                0.0s 
 => [internal] load metadata for docker.io/subfuzion/dart:slim                                                                  1.4s 
 => [internal] load metadata for docker.io/google/dart:2.10                                                                     1.7s 
 => [jubarte2server-aot 1/16] FROM docker.io/subfuzion/dart:slim@sha256:1a60fa1089065c4dd86d0735becafab9d14dca828ba0ee19ab6b54  0.0s 
 => [internal] load build context                                                                                               0.4s 
 => => transferring context: 4.84kB                                                                                             0.0s 
 => [jubarte2server 1/8] FROM docker.io/google/dart:2.10@sha256:ee2eace7c54696a43ba0f7db7ebeacf0b851d199cecd3bf4d7e3863a01dcbb  0.0s 
 => CACHED [jubarte2server 2/8] WORKDIR /app                                                                                    0.0s 
 => CACHED [jubarte2server 3/8] ADD pubspec.* /app/                                                                             0.0s 
 => CACHED [jubarte2server 4/8] RUN pub get --no-precompile                                                                     0.0s 
 => CACHED [jubarte2server 5/8] ADD . /app                                                                                      0.0s 
 => CACHED [jubarte2server 6/8] RUN pub get --offline                                                                           0.0s 
 => [jubarte2server 7/8] RUN cp .env.example.linux /app/.env                                                                    1.3s 
 => [jubarte2server 8/8] RUN dart compile exe /app/bin/prod.dart -o /app/bin/prod                                              21.3s 
 => CACHED [jubarte2server-aot 2/16] COPY --from=jubarte2server /bin/sh /bin/sh                                                 0.0s 
 => CACHED [jubarte2server-aot 3/16] COPY --from=jubarte2server /bin/bash /bin/bash                                             0.0s 
 => CACHED [jubarte2server-aot 4/16] COPY --from=jubarte2server /bin/ls /bin/ls                                                 0.0s 
 => CACHED [jubarte2server-aot 5/16] COPY --from=jubarte2server /lib/x86_64-linux-gnu/libpcre.so.3 /lib/x86_64-linux-gnu/libpc  0.0s
 => CACHED [jubarte2server-aot 6/16] COPY --from=jubarte2server /lib/x86_64-linux-gnu/libselinux.so.1 /lib/x86_64-linux-gnu/li  0.0s 
 => CACHED [jubarte2server-aot 7/16] COPY --from=jubarte2server /lib/x86_64-linux-gnu/libtinfo.so.6 /lib/x86_64-linux-gnu/libt  0.0s 
 => CACHED [jubarte2server-aot 8/16] COPY --from=jubarte2server /lib/x86_64-linux-gnu/libdl.so.2 /lib/x86_64-linux-gnu/libdl.s  0.0s
 => CACHED [jubarte2server-aot 9/16] COPY --from=jubarte2server /lib/x86_64-linux-gnu/libc.so.6 /lib/x86_64-linux-gnu/libc.so.  0.0s 
 => CACHED [jubarte2server-aot 10/16] COPY --from=jubarte2server /app/.env /app/bin/.env                                        0.0s 
 => CACHED [jubarte2server-aot 11/16] COPY --from=jubarte2server /app/.env /.env                                                0.0s 
 => CACHED [jubarte2server-aot 12/16] COPY --from=jubarte2server /app/.env /usr/lib/.env                                        0.0s 
 => CACHED [jubarte2server-aot 13/16] COPY --from=jubarte2server /app/.env /usr/bin/.env                                        0.0s
 => CACHED [jubarte2server-aot 15/16] COPY --from=jubarte2server /app/.env /tmp/.env                                            0.0s 
 => [jubarte2server-aot 16/16] COPY --from=jubarte2server /app/bin/prod /app/bin/prod                                           1.2s 
 => exporting to image                                                                                                          2.4s 
 => => exporting layers                                                                                                         0.6s 
 => => writing image sha256:8496a75b81bf15c20b38fa8eb8854f7833e5d78afa962933b9708b0d15835f38                                    0.1s 
 => => naming to docker.io/library/jubarte2server-aot                                                                           0.1s 
PS D:\MyDartProjects\jubarte2\jubarte2server> docker run -e "dbhost=192.168.133.13" -i --name jubarte2server-aot -p 3150:3150 jubarte2server-aot
____________   ________________________ 
___    |__  | / /_  ____/__  ____/__  /
__  /| |_   |/ /_  / __ __  __/  __  /
_  ___ |  /|  / / /_/ / _  /___  _  /___
/_/  |_/_/ |_/  ____/  /_____/  /_____/

A batteries-included, full-featured, full-stack framework in Dart.

https://angel-dart.github.io

Starting `jubarte_angel` application...
[INFO] jubarte_angel: boot_angel.dart  /api APP_ENV: production
[INFO] jubarte_angel: db_connect.dart dbConnect() connect Jubarte localhost
[INFO] jubarte_angel: db_connect.dart dbConnect() connect BlogBIT 192.168.133.22
[INFO] jubarte_angel: db_connect.dart dbConnect() connect CEP 10.0.0.22
[INFO] jubarte_angel: boot_angel.dart  /api APP_ENV: production
[INFO] jubarte_angel: db_connect.dart dbConnect() connect Jubarte localhost
[INFO] jubarte_angel: db_connect.dart dbConnect() connect BlogBIT 192.168.133.22
[INFO] jubarte_angel: db_connect.dart dbConnect() connect CEP 10.0.0.22
[INFO] jubarte_angel: Instance #1 listening at http://127.0.0.1:3000
[INFO] jubarte_angel: Instance #0 listening at http://127.0.0.1:3000


```
Only the JIT version with your image is having a problem, because with the official google/dart image it works normal

**Comment by insinfo** [comment] 2020-11-30 20:47
at first I thought the problem would not be finding the .env file because I had this problem in the AOT image, but later I saw that the problem is not this, for now I can't understand what the problem is, because this error message does not help much.
I don't know if it's related to that
https://github.com/dart-lang/sdk/issues/41057#issuecomment-736052067

any suggestion of a possible solution would be very good

**Comment by subfuzion** [comment] 2020-12-01 03:30
@insinfo It helps if you also copy the error you're seeing so I don't have to guess what the problem is!

Without seeing the error, I'm guessing that perhaps you need at least `/usr/lib/dart/lib/_internal/dartdev.dill` (and possibly other *.dill files under `/usr/lib/dart/lib/_internal`.

Instead of just this:

```
FROM subfuzion/dart:slim as jubarte2server-jit
COPY --from=jubarte2server /usr/lib/dart/bin/dart /usr/lib/dart/bin/dart
```

try this:

```
FROM subfuzion/dart:slim as jubarte2server-jit
COPY --from=jubarte2server /usr/lib/dart/bin/dart /usr/lib/dart/bin/
COPY --from=jubarte2server /usr/lib/dart/lib/_internal/dartdev.dill /usr/lib/dart/lib/_internal/
```

If that doesn't work, just copy all the *.dill to see if that works (that will add ~around 70MB to the image).

```
FROM subfuzion/dart:slim as jubarte2server-jit
COPY --from=jubarte2server /usr/lib/dart/bin/dart /usr/lib/dart/bin/dart
COPY --from=jubarte2server /usr/lib/dart/lib/_internal/*.dill /usr/lib/dart/lib/_internal/
```

Reopening this issue. Let me know if this solution works for you.

If this doesn't solve the issue, it would be helpful if you give me access to your repo or create a separate private repo with a self contained example that fails to build, invite me as a collaborator, and I will try to replicate the issue. At the very least I need you to share the error message, or else it's quite hard to guess what the problem is. The only clue came from your updated messages when you said it worked with AOT build but not a JIT build (and then linked to another repo comment). This tells me the image is missing one or more additional runtime support shared libs. Hopefully you are now able to solve the problem.

**Comment by subfuzion** [comment] 2020-12-01 10:12
@insinfo The repo has been updated to address the need to copy any necessary *.dill files. See the [Dart VM](https://github.com/subfuzion/dart-docker-slim#dart-vm) section for more details.

Out of curiosity, since you can successfully build the AOT version, why do you want to build the JIT version? Is it for faster builds?

**Comment by insinfo** [comment] 2020-12-01 14:46
The question of executing the two images in the AOT version and the JIT was to test the performance because in the past the AOT performance of the dart did not deliver good performance


The error message that was appearing was this

> Unable to find DartDev snapshot


 this solved the problem
```Dockerfile
COPY --from=jubarte2server /usr/lib/dart/lib/_internal/dartdev.dill /usr/lib/dart/lib/_internal/

```

![image](https://user-images.githubusercontent.com/12227024/100754894-58bb1c80-33ca-11eb-968e-aa2182c9a87a.png)

![image](https://user-images.githubusercontent.com/12227024/100754941-65d80b80-33ca-11eb-9f51-72464417f9d8.png)


It was 157 megabytes, much better than the 780 megabytes of the google/dart image

final JIT Dockerfile working
```Dockerfile
FROM google/dart:2.10 as jubarte2server
WORKDIR /app
ADD pubspec.* /app/
RUN pub get --no-precompile
ADD . /app
RUN pub get --offline
RUN cp .env.example.linux .env
#RUN dart compile kernel -o bin/prod.dill bin/prod.dart

FROM subfuzion/dart:slim as jubarte2server-jit
COPY --from=jubarte2server /usr/lib/dart/bin/dart /usr/lib/dart/bin/dart
COPY --from=jubarte2server /usr/lib/dart/lib/_internal/dartdev.dill /usr/lib/dart/lib/_internal/
COPY --from=jubarte2server /root/.pub-cache /root/.pub-cache
COPY --from=jubarte2server /app /app
COPY --from=jubarte2server /app/.env /.env
#COPY --from=jubarte2server /app/.env /app/bin/.env 
#COPY --from=jubarte2server /app/.env /usr/lib/dart/bin/.env 
ENV dbhost=localhost
EXPOSE 3150
#--disable-dart-dev
ENTRYPOINT ["/usr/lib/dart/bin/dart","run","/app/bin/prod.dart", "-p", "3150", "-a" ,"0.0.0.0","--dbhost=$dbhost"]
# docker build -f Dockerfile_jit -t jubarte2server-jit .
# executa a imagem
# docker run -e "dbhost=192.168.133.13" -d --name jubarte2server-jit -p 3150:3150 jubarte2server-jit   
# docker run -e "dbhost=192.168.133.13" -i --name jubarte2server-jit -p 3150:3150 jubarte2server-jit   


```

**Comment by insinfo** [comment] 2020-12-01 14:52
without copying this "lib /_internal/dartdev.dill" worked by passing the parameter "--disable-dart-dev" to dart VM, but I don't know the impact of this on the application

**Comment by subfuzion** [comment] 2020-12-01 20:25
@insinfo Make sense. AOT compiled apps have faster start time and more consistent performance; JIT compiled apps take longer to start, but can potentially run faster than AOT compiled apps over time. It makes sense for long-running servers, but not necessarily ideal in containerized environments where you want autoscaling to happen to tasks to respond to events as quickly and responsively as possible. Thanks for the feedback and good luck!

**Closed as completed by subfuzion** 2020-12-01 20:25 UTC
Labels: bug
